import { FileText, Search, ArrowRight, Calendar } from 'lucide-react'

export interface Quote {
  id: number
  title: string
  company: string
  amount: number
  dueDate: string
  status: string
}

interface QuotesPageProps {
  onOpenQuoteDetail?: (quote: Quote) => void
}

const QuotesPage = ({ onOpenQuoteDetail }: QuotesPageProps) => {
  const userName = 'Nirmal'

  const dueThisWeek = [
    {
      id: 1,
      title: 'Custom CRM Integration',
      company: 'Startup Hub',
      amount: 28000,
      dueDate: '1/29/2025',
      status: 'READY TO SEND',
    },
    {
      id: 2,
      title: 'SaaS License Expansion',
      company: 'Blue Service Corp',
      amount: 15500,
      dueDate: '1/31/2025',
      status: 'READY TO SEND',
    },
    {
      id: 3,
      title: 'AI Analytics Pilot',
      company: 'Tech Labs Inc',
      amount: 9200,
      dueDate: '1/30/2025',
      status: 'READY TO SEND',
    },
  ]

  const dueNextWeek = [
    {
      id: 4,
      title: 'Enterprise Security Audit',
      company: 'FinanceHub',
      amount: 12000,
      dueDate: '2/5/2025',
      status: 'READY TO SEND',
    },
    {
      id: 5,
      title: 'Infrastructure Resilience Pack',
      company: 'CloudTech Systems',
      amount: 42000,
      dueDate: '2/8/2025',
      status: 'READY TO SEND',
    },
    {
      id: 6,
      title: 'Mobile App Revamp',
      company: 'Swift Digital',
      amount: 65000,
      dueDate: '2/10/2025',
      status: 'READY TO SEND',
    },
  ]

  const totalQuotes = dueThisWeek.length + dueNextWeek.length
  const totalValue = [...dueThisWeek, ...dueNextWeek].reduce(
    (sum, quote) => sum + quote.amount,
    0
  )

  return (
    <>
      <div className='bg-slate-900/30 border-b border-slate-700/50'>
        <div className='max-w-[1600px] mx-auto px-8 py-12'>
          <h1 className='text-4xl font-light text-white mb-4'>
            Hi {userName}, you have{' '}
            <span className='text-blue-400 font-semibold'>
              {totalQuotes} quotes
            </span>{' '}
            ready for dispatch this week.
          </h1>
          <p className='text-base text-blue-300 leading-relaxed max-w-4xl'>
            You have a surge of momentum with {totalQuotes} quotes in the 'Quote
            Ready' stage, totaling over ${(totalValue / 1000).toFixed(1)}K. Most
            urgent is the ${(dueThisWeek[0].amount / 1000).toFixed(1)}K{' '}
            {dueThisWeek[0].title} for {dueThisWeek[0].company}, which is due
            today. You also have a $
            {(dueNextWeek[dueNextWeek.length - 1].amount / 1000).toFixed(0)}K
            hardware refresh proposal for{' '}
            {dueNextWeek[dueNextWeek.length - 1].company} that needs to be
            finalized before next week's deadline.
          </p>
        </div>
      </div>

      <main className='max-w-[1600px] mx-auto px-8 py-10'>
        <div className='mb-8'>
          <div className='flex items-center justify-between mb-6'>
            <div>
              <h2 className='text-2xl font-semibold text-white mb-2'>
                Quotes Command Center
              </h2>
              <p className='text-sm text-blue-300'>
                Dispatch high-stakes proposals generated by AI
              </p>
            </div>
            <div className='relative'>
              <Search className='absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400' />
              <input
                type='text'
                placeholder='Filter proposals...'
                className='w-80 pl-11 pr-4 py-2.5 bg-slate-800/50 border border-slate-700 rounded-lg text-sm text-white placeholder-slate-400 focus:outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20'
              />
            </div>
          </div>
        </div>

        <div className='mb-12'>
          <h3 className='text-xl font-semibold text-white mb-6'>
            DUE THIS WEEK
          </h3>
          <div className='grid grid-cols-3 gap-6'>
            {dueThisWeek.map(quote => (
              <div
                key={quote.id}
                className='bg-white rounded-2xl shadow-lg overflow-hidden hover:shadow-xl transition-all'
              >
                <div className='p-7'>
                  <div className='flex items-start justify-between mb-5'>
                    <div className='w-12 h-12 bg-slate-900 flex items-center justify-center rounded-xl shadow-md'>
                      <FileText className='w-6 h-6 text-white' />
                    </div>
                    <div className='text-right'>
                      <div className='text-xs text-slate-500 uppercase tracking-wider mb-1'>
                        POTENTIAL
                      </div>
                      <div className='text-2xl font-bold text-slate-900'>
                        ${quote.amount.toLocaleString()}
                      </div>
                    </div>
                  </div>

                  <h4 className='text-lg font-bold text-slate-900 mb-2'>
                    {quote.title}
                  </h4>
                  <p className='text-sm text-slate-600 mb-5'>{quote.company}</p>

                  <div className='flex items-center gap-2 mb-6 text-sm'>
                    <Calendar className='w-4 h-4 text-blue-500' />
                    <span className='font-semibold text-slate-900'>
                      DUE: {quote.dueDate}
                    </span>
                  </div>

                  <button
                    onClick={() => onOpenQuoteDetail?.(quote)}
                    className='w-full py-3.5 px-4 bg-slate-900 text-white text-sm font-normal hover:bg-slate-800 transition-colors flex items-center justify-between'
                    style={{ borderRadius: '0.35rem' }}
                  >
                    <span>Builder Ready</span>
                    <ArrowRight className='w-4 h-4' />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div>
          <h3 className='text-xl font-semibold text-white mb-6'>
            DUE NEXT WEEK
          </h3>
          <div className='grid grid-cols-3 gap-6'>
            {dueNextWeek.map(quote => (
              <div
                key={quote.id}
                className='bg-white rounded-2xl shadow-lg overflow-hidden hover:shadow-xl transition-all'
              >
                <div className='p-7'>
                  <div className='flex items-start justify-between mb-5'>
                    <div className='w-12 h-12 bg-slate-900 flex items-center justify-center rounded-xl shadow-md'>
                      <FileText className='w-6 h-6 text-white' />
                    </div>
                    <div className='text-right'>
                      <div className='text-xs text-slate-500 uppercase tracking-wider mb-1'>
                        POTENTIAL
                      </div>
                      <div className='text-2xl font-bold text-slate-900'>
                        ${quote.amount.toLocaleString()}
                      </div>
                    </div>
                  </div>

                  <h4 className='text-lg font-bold text-slate-900 mb-2'>
                    {quote.title}
                  </h4>
                  <p className='text-sm text-slate-600 mb-5'>{quote.company}</p>

                  <div className='flex items-center gap-2 mb-6 text-sm'>
                    <Calendar className='w-4 h-4 text-blue-500' />
                    <span className='font-semibold text-slate-900'>
                      DUE: {quote.dueDate}
                    </span>
                  </div>

                  <button
                    onClick={() => onOpenQuoteDetail?.(quote)}
                    className='w-full py-3.5 px-4 bg-slate-900 text-white text-sm font-normal hover:bg-slate-800 transition-colors flex items-center justify-between'
                    style={{ borderRadius: '0.35rem' }}
                  >
                    <span>Builder Ready</span>
                    <ArrowRight className='w-4 h-4' />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  )
}

export default QuotesPage
